### ISSUE TITLE
Crash with OPAC (BOMD-1.5.1-1.19.3.jar)

### ISSUE THREAD

**Issue by gamerpotion** [miyo6032/bosses-of-mass-destruction#100]
Hi, am using this in my modpack. Recently had a crash shown up in the logs and when I queried it with the OPAC author they said it was to do with this mod, please see below

running on Fabric 1.19.3
BOMD-1.5.1-1.19.3.jar
open-parties-and-claims-fabric-1.19.3-0.17.5.jar

```
Xaero96
Very strange. Why would an "attack entity" event even be fired with the attacked entity being null? How is that even an attack in that case?
I think it might be caused by multipart_entities. Where did you get that mod? I can't find it.
```

```
[17:43:21] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "target" is null
	at xaero.pac.common.event.CommonEvents.onEntityAttack(CommonEvents.java:259) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at xaero.pac.common.event.CommonEventsFabric.onEntityAttack(CommonEventsFabric.java:186) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.4+3baeb27a85-fb4f9c402cca741f.jar:?]
	at net.minecraft.class_3222.handler$bmk000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:9317) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at io.github.stuff_stuffs.multipart_entities.common.network.PlayerInteractMultipartReceiver.lambda$receive$0(PlayerInteractMultipartReceiver.java:34) ~[multipart_entities-1.3-1.19.3-rc1-20ad779a2de91690.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:21] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "target" is null
	at xaero.pac.common.event.CommonEvents.onEntityAttack(CommonEvents.java:259) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at xaero.pac.common.event.CommonEventsFabric.onEntityAttack(CommonEventsFabric.java:186) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.4+3baeb27a85-fb4f9c402cca741f.jar:?]
	at net.minecraft.class_3222.handler$bmk000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:9317) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at io.github.stuff_stuffs.multipart_entities.common.network.PlayerInteractMultipartReceiver.lambda$receive$0(PlayerInteractMultipartReceiver.java:34) ~[multipart_entities-1.3-1.19.3-rc1-20ad779a2de91690.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:21] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "target" is null
	at xaero.pac.common.event.CommonEvents.onEntityAttack(CommonEvents.java:259) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at xaero.pac.common.event.CommonEventsFabric.onEntityAttack(CommonEventsFabric.java:186) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.4+3baeb27a85-fb4f9c402cca741f.jar:?]
	at net.minecraft.class_3222.handler$bmk000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:9317) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at io.github.stuff_stuffs.multipart_entities.common.network.PlayerInteractMultipartReceiver.lambda$receive$0(PlayerInteractMultipartReceiver.java:34) ~[multipart_entities-1.3-1.19.3-rc1-20ad779a2de91690.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:21] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "target" is null
	at xaero.pac.common.event.CommonEvents.onEntityAttack(CommonEvents.java:259) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at xaero.pac.common.event.CommonEventsFabric.onEntityAttack(CommonEventsFabric.java:186) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.4+3baeb27a85-fb4f9c402cca741f.jar:?]
	at net.minecraft.class_3222.handler$bmk000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:9317) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at io.github.stuff_stuffs.multipart_entities.common.network.PlayerInteractMultipartReceiver.lambda$receive$0(PlayerInteractMultipartReceiver.java:34) ~[multipart_entities-1.3-1.19.3-rc1-20ad779a2de91690.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:21] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "target" is null
	at xaero.pac.common.event.CommonEvents.onEntityAttack(CommonEvents.java:259) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at xaero.pac.common.event.CommonEventsFabric.onEntityAttack(CommonEventsFabric.java:186) ~[open-parties-and-claims-fabric-1.19.3-0.17.5.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackEntityCallback.lambda$static$0(AttackEntityCallback.java:44) ~[fabric-events-interaction-v0-0.4+3baeb27a85-fb4f9c402cca741f.jar:?]
	at net.minecraft.class_3222.handler$bmk000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3222.java:9317) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at io.github.stuff_stuffs.multipart_entities.common.network.PlayerInteractMultipartReceiver.lambda$receive$0(PlayerInteractMultipartReceiver.java:34) ~[multipart_entities-1.3-1.19.3-rc1-20ad779a2de91690.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5917) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by miyo6032** [comment]
multipart_entities is a fork of some utility mod - i will look when i have time

**Comment by miyo6032** [comment]
i cannot replicate this on 1.20, let me know if you encounter it an how to replicate exactly
