### ISSUE TITLE
Game crashing on opening (I have all the dependencies).

### ISSUE THREAD

**Issue by KashiiGang** [miyo6032/bosses-of-mass-destruction#112]
Here's the crash report

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-12-02, 10:22 p.m.
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bosses_of_mass_destruction'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.barribob.maelstrom.MaelstromMod
		at net.barribob.maelstrom.MaelstromModKt.init(MaelstromMod.kt:53)
		at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
		at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy36.onInitialize(Unknown Source)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
Caused by: java.lang.NoSuchFieldError: serverEventScheduler
	at net.barribob.maelstrom.MaelstromMod.<clinit>(MaelstromMod.kt:30)
	at net.barribob.boss.MainKt.init(Main.kt:57)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy36.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more

**Comment by miyo6032** [comment]
uploaded a fix 1.3.10

**Comment by KashiiGang** [comment]
Works now. Thank you
