### ISSUE TITLE
Crash on 1.17

### ISSUE THREAD

**Issue by coco9515** [miyo6032/bosses-of-mass-destruction#13]
The crash happened on the start load, the error is : 
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bosses_of_mass_destruction'!
Code de sortie : -1
```

<details>
  <summary>And the crashlog : </summary>
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/20/21, 9:10 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bosses_of_mass_destruction'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: software/bernie/geckolib3/GeckoLib
	at net.barribob.boss.MainKt.init(MainKt.java:45)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:194)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy35.onInitialize(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.GeckoLib
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1788609024 bytes (1705 MiB) / 2629828608 bytes (2508 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6663
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37548.70
	Virtual memory used (MB): 20414.57
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 85.50
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.17-fabric0.34.9-1.2.1
		amecsapi: Amecs API 1.1.4+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.0.9
		armorhotswap: ArmorHotswap 1.1
		atmosfera: Atmosfera 1.4.0+mc1.17
		authme: Auth Me 1.5.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		bettermounthud: Better Mount HUD 1.1.0
		betternether: Better Nether 5.1.0
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.1-1.17
		caelus: Caelus API 0.0.16-1.17
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		cavebiomes: Cave Biomes 0.6.3
		cavenabler: Cavenabler 1.0.0
		centeredinventory: Centered inventory 1.0.3
		cherishedworlds: Cherished Worlds 1.4.1-1.17
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		clumps: Clumps fabric-1.17-7.0.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		controlling: Controlling For Fabric 1.1.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		dawn: Dawn API 2.0.3
		dragonloot: DragonLoot 1.0.8
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		earthtojavamobs: Earth2Java 1.7.1+1.17
		elementalcreepers: Elemental Creepers: Refabricated 1.4.0
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchantmentdescriptions: Enchantment Descriptions 3.0.11
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.0+1.17
		fastfurnace: FastFurnace 1.17-3.0
		firstperson: FirstpersonModel ${version}
		grindenchantments: Grind Enchantments 1.2.0+1.17
		haulinghog: Hauling Hog 1.0.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		hydrogen: Hydrogen 0.3
		inventorysorter: Inventory Sorter 1.7.9-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kappa: Kappa 3.0.0
		kirin: Kirin UI 1.8.7-1.17
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lakeside: Lakeside 1.1.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lchunkloader: Literally Chunk Loader 2.0.3
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.0
		linkedstorage: Linked Storage 1.3.11-1.17
		lithium: Lithium 0.7.1
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		magic_mirror: Magic Mirror 1.2.3
		maptooltip: Map Tooltip 1.3.0
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.2.2
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmenu: Mod Menu 2.0.2
		moenchant_lib: Mo'Enchantment Library 0.1.0
		moenchantments: Mo'Enchantments 1.17.3
		moremessages: MoreMessages 1.2.0
		morevillagers-fabric: MoreVillagersFabric 2.0.0-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		multipart_entities: MultipartEntities 1.1.2-1.17
		musicdr: Music Duration Reducer 1.2.1
		namepain: Name Pain 1.4.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		npcvariety: NPC Variety 2.0.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		powershot: Powershot 1.2.0-1.17-fabric
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		promenade: Promenade 2.1.2
		realisticfirespread: Realistic Fire Spread 1.17-1
		respawnablepets: Respawnable Pets 1.17-1
		ring_of_enderchest: Ring of Enderchest 1.1.6
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0-alpha.4+1.17
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.7
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terrarianslimes: Terrarian Slimes 1.0.5-BETA+1.17
		transliterationlib: TRansliterationLib 1.1.0
		transportables: Transportables 1.0.5
		trees-do-not-float: Trees Do Not Float 2.1.142
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed: Tweed 3.0.0-beta.26
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagernames: Villager Names 2.0.0
		visualoverhaul: VisualOverhaul 3.3.0
		voicechat: Simple Voice Chat 1.17-1.1.5
		waterdripsound: Drip Sounds 1.17-0.2.1
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		woods_and_mires: Woods and Mires 1.1.0+1.17
		wthit: wthit 3.5.3
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```
</details>

**Comment by miyo6032** [comment]
Geckolib does not seem to be on the modlist. Include that and it should work

**Comment by coco9515** [comment]
I found why it doesn't auto download it !

The requirement is set for "geckolib", which is not updated to 1.17, they ask to use this version (that has been updated) : https://www.curseforge.com/minecraft/mc-mods/geckolib

You should change the requirement of your mod for the Curseforge launcher to auto-download it properly then.

**Comment by miyo6032** [comment]
Many thanks, will do
