### ISSUE TITLE
Creating game glitch

### ISSUE THREAD

**Issue by mikaboshikami** [miyo6032/bosses-of-mass-destruction#20]
I can get in minecraft all fine but while generating a world it crashes, this is the text that comes up.

The game crashed whilst feature placement
Error: dev.onyxstudios.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Bosses of Mass Destruction (Beta) (bosses_of_mass_destruction)
Exit Code: -1

Oh I forgot heres the crash report -

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 16/07/2021, 19:52
Description: Feature placement

dev.onyxstudios.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Bosses of Mass Destruction (Beta) (bosses_of_mass_destruction)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:157)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:110)
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:69)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:68)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:63)
	at net.minecraft.class_1297.handler$blh000$initDataTracker(class_1297.java:13032)
	at net.minecraft.class_1297.<init>(class_1297.java:280)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:122)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_1642.<init>(class_1642.java:93)
	at net.minecraft.class_1551.<init>(class_1551.java:68)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.minecraft.class_3409$class_3410.method_15026(class_3409.java:239)
	at net.minecraft.class_3470.method_14931(class_3470.java:95)
	at net.minecraft.class_3409$class_3410.method_14931(class_3409.java:260)
	at net.minecraft.class_3449.method_14974(class_3449.java:97)
	at net.minecraft.class_1959.method_28401(class_1959.java:366)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_1959.method_8702(class_1959.java:365)
	at net.minecraft.class_2794.method_12102(class_2794.java:245)
	at net.minecraft.class_2806.method_12151(class_2806.java:100)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/world/WorldComponentInitializer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:154)
	... 52 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.world.WorldComponentInitializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 66 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:157)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:110)
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:69)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:68)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:63)
	at net.minecraft.class_1297.handler$blh000$initDataTracker(class_1297.java:13032)
	at net.minecraft.class_1297.<init>(class_1297.java:280)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:122)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_1642.<init>(class_1642.java:93)
	at net.minecraft.class_1551.<init>(class_1551.java:68)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.minecraft.class_3409$class_3410.method_15026(class_3409.java:239)
	at net.minecraft.class_3470.method_14931(class_3470.java:95)
	at net.minecraft.class_3409$class_3410.method_14931(class_3409.java:260)
	at net.minecraft.class_3449.method_14974(class_3449.java:97)
	at net.minecraft.class_1959.method_28401(class_1959.java:366)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/structure_feature / minecraft:ocean_ruin]
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:365)

-- Generation --
Details:
	CenterX: 6
	CenterZ: 5
	Seed: -3059800974715206486
	Biome: net.minecraft.class_1959@33649fde
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:245)
	at net.minecraft.class_2806.method_12151(class_2806.java:100)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)

-- Chunk to be generated --
Details:
	Location: 6,5
	Position hash: 21474836486
	Generator: net.minecraft.class_3754@6c5bdba8
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 992
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: mod test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:401)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350)
	at net.minecraft.class_1132.method_3823(class_1132.java:71)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 653117440 bytes (622 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=26.21.14.4223
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22328.55
	Virtual memory used (MB): 11812.11
	Swap memory total (MB): 14294.25
	Swap memory used (MB): 1159.64
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.2.21
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.3-1.17
		axolotlitemfix: Axolotl Item Fix 1.1.1
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		bedspreads: Bedspreads 1.4.0-1.17
		beebuddy: Bee Buddies 1.1.3+1.17.1
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		bendy-lib: Bendy api 2.0.2
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.9-fabric
		bluemap: BlueMap 1.5.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.2-1.17
		cakechomps: Cake Chomps 1.4.0-1.17
		calio: Calio 1.0.1
		canvas: Canvas Renderer 1.0.1762
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carvepump: Carve My Pumpkin 1.0.4
		clear-skies: Clear Skies 1.5.69
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		clumps: Clumps fabric-1.17-7.0.0.2
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		custom-fog: Custom Fog 1.6.0
		dangerousstonecutter: Dangerous Stone Cutter 1.5
		doggomod: Doggo Mod 1.0.2
		dontbreakme: Don't Mine Me 1.1
		easyzillagers: Easy Zillagers 1.0.0
		elementalcreepers: Elemental Creepers: Refabricated 1.4.0
		emotecraft: Emotecraft 2.0.8
		entitybanners: Entity Banners 1.0.1-BETA+1.17
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricenchantments: Fabric Enchantments 0.3.0
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fancymenu: FancyMenu 2.1.2
		fermion: Fermion 2.11.243
		fermion-orientation: Fermion Orientation 1.2.243
		fermion-varia: Fermion Varia 2.6.243
		fiber: fiber 0.23.0-2
		forgottenrecipes: Forgotten Recipes 1.0.1
		frex: FREX 5.2.225
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.8
		golfiv: Golf IV 0.3.2
		grondag_bitraster: bitraster 1.4.12
		image2map: Image2Map 0.2.1
		invview: InvView 1.4.5-1.17.1+
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		json-model-extensions: JSON Model Extensions 1.22.201
		konkrete: Konkrete 1.2.1
		lambdynlights: LambDynamicLights 2.0.1+1.17
		libgui: LibGui 4.1.1+1.17.1-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		locationsmod: LocationsMod 1.2
		lumiwool: Luminous Wool 1.1.1
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		minecraft: Minecraft 1.17.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmenu: Mod Menu 2.0.2
		moreberries: More Berries 1.4.2
		moremessages: MoreMessages 1.3.0
		multipart_entities: MultipartEntities 1.1.2-1.17
		no_sneaking_over_magma: No Sneaking Over Magma! 1.0.8+MC1.17-1.17.1
		noannoyingsettings: NoAnnoyingSettings 1.2
		nv_fade: Night Vision Fade 1.0.0
		omega-config: OmegaConfig 1.0.8
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		pigpoop: Pig Poop 1.0.0
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		quicksand: Quicksand 1.0.2
		quickspyglasser: Quick Spyglasser 0.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		roughlysearchable: Roughly Searchable 2.2.0+1.17.1
		sgui: SGui 1.0.0-rc3-1.17.1
		simple_utilities: Simple HUD Utilities 2.2.0
		skinswapper: Skin Swapper 2.1.0
		slimechunkf3: SlimeChunkF3 1.2
		slimeorigin: Slimeorigin 4.0.0
		special-circumstances: Special Circumstances 1.9.243
		spruceui: SpruceUI 3.2.0+1.17
		structurized: Structurized 1.3.0
		tacocraft: TacoCraft 1.6.4-1.17.1
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		troll_commands: Troll Commands 1.1.0
		zombified: Zombified 1.0.0
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by miyo6032** [comment]
You seem to only have a couple of modules of Cardinal Components - download the Cardinal Components jar in your mods folder.

**Comment by mikaboshikami** [comment]
I have the Cardinal Components Api mod and it is in my mod folder already 
![image](https://user-images.githubusercontent.com/79607904/126038793-90ce3cb7-2e46-4852-8d51-c0b04bf0b1d7.png)
so i am not really sure why it is happening

**Comment by miyo6032** [comment]
On second look, look like you both have  2.8.3 and 3.0.0 versions of cardinal components. I'm guessing some mod has packaged the 3.0.0 version within its jar and maybe that is messing it up. You can try and get the alpha 3.0.0 version, but I don't know if it will work.

**Comment by mikaboshikami** [comment]
It didn't work. It still crashes at the same time even without cardinal components in my mods folder, also cardinal components on curseforge doesn't have 3.0.0 on the site the mod directs me to. https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3312678 I'm not sure if there is another website or if the problem is something different. There shouldn't be a mod I have that has cardinal components in it and if it does it should work. Another problem that sometimes happens is that the world loader gets stuck like this. 
![image](https://user-images.githubusercontent.com/79607904/126084741-7b4d8675-7030-48e0-ab83-290c5fcdcd49.png)
Sorry if this problem is a hassle to work with!

**Comment by miyo6032** [comment]
This is 3.0.1 https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3380730

**Comment by mikaboshikami** [comment]
Oh, with that mod it works! On the mod page the link it shares to me on the relations tab is this one https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files which only lets you download the old version which is why I got the issues. Thank you for the help!
