### ISSUE TITLE
Game crashes @ starup

### ISSUE THREAD

**Issue by memejim8** [miyo6032/bosses-of-mass-destruction#34]
MultiMC version: 0.6.13-develop-2511

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [54.192.9.68]

session.minecraft.net resolves to:
    [3.234.0.54, 52.44.210.220, 34.192.50.106]

textures.minecraft.net resolves to:
    [52.85.156.55, 52.85.156.2, 52.85.156.95, 52.85.156.71]

api.mojang.com resolves to:
    [52.85.221.105]

Minecraft folder is:
D:/Desktop/BiosUpdater.exe/MultiMC/instances/1.17.1/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  D:/Desktop/BiosUpdater.exe/MultiMC/instances/1.17.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/fabric-loader/0.11.7/fabric-loader-0.11.7.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/minecraft/1.17.1/minecraft-1.17.1-client.jar

Native libraries:
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/Desktop/BiosUpdater.exe/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] bedspreads-fabric-1.4.0-1.17.jar (disabled)
  [✔️] BOMD-1.2.3-1.17.1
  [✔️] Cardinal-Components-API-3.1.1
  [✔️] cloth-config-5.0.38-fabric
  [✔️] fabric-api-0.40.1+1.17
  [✔️] fabric-language-kotlin-1.6.4+kotlin.1.5.30
  [✔️] geckolib-1.17.1-3.0.2
  [❌] iris-and-sodium-mc1.17-1.1.2+build.9.jar (disabled)
  [❌] outvoted-1.16.5-1.2.4.jar (disabled)
  [❌] RoughlyEnoughItems-6.0.279-alpha-fabric.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir D:/Desktop/BiosUpdater.exe/MultiMC/instances/1.17.1/.minecraft --assetsDir D:/Desktop/BiosUpdater.exe/MultiMC/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 28116

Using onesix launcher.

[12:08:14] [main/INFO]: Loading for game Minecraft 1.17.1
[12:08:15] [ForkJoinPool-1-worker-31/WARN]: Non-Fabric mod JAR at "D:\Desktop\BiosUpdater.exe\MultiMC\instances\1.17.1\.minecraft\mods\geckolib-1.17.1-3.0.2.jar", ignoring
[12:08:15] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afa13, also found 0.3.2+92519afa18
[12:08:15] [main/INFO]: [FabricLoader] Loading 72 mods:
	- bosses_of_mass_destruction@1.2.3-1.17.1
	- cardinal-components@3.1.1
	- cardinal-components-base@3.1.1
	- cardinal-components-block@3.1.1
	- cardinal-components-chunk@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-item@3.1.1
	- cardinal-components-level@3.1.1
	- cardinal-components-scoreboard@3.1.1
	- cardinal-components-util@3.1.1
	- cardinal-components-world@3.1.1
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- fabric@0.40.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+cbda931818
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.3+4658223018
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.4+4658223018
	- fabric-rendering-v1@1.8.2+ffb6d41e18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+cbda931818
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.3.1+4658223018
	- fabricloader@0.11.7
	- java@16
	- maelstrom_library@1.2.1-1.17
	- minecraft@1.17.1
	- multipart_entities@1.1.2-1.17
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
[12:08:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/Desktop/BiosUpdater.exe/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[12:08:15] [main/INFO]: Compatibility level set to JAVA_16
[12:08:16] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[12:08:21] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:08:22] [Render thread/INFO]: Setting user: m3m3_j1m_8
[12:08:22] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbl000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/21/21, 12:08 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bosses_of_mass_destruction'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: software/bernie/geckolib3/GeckoLib
	at net.barribob.boss.MainKt.init(MainKt.java:45)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:194)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy29.onInitialize(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more
Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.GeckoLib
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1059627200 bytes (1010 MiB) / 1965031424 bytes (1874 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.22025.1006
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 51150.88
	Virtual memory used (MB): 26943.88
	Swap memory total (MB): 34816.00
	Swap memory used (MB): 1346.52
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx4096m
	Fabric Mods: 
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.17.1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.7
		java: Java HotSpot(TM) 64-Bit Server VM 16
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		minecraft: Minecraft 1.17.1
		multipart_entities: MultipartEntities 1.1.2-1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\Desktop\BiosUpdater.exe\MultiMC\instances\1.17.1\.minecraft\crash-reports\crash-2021-09-21_12.08.23-client.txt
Process exited with code -1.
Clipboard copy at: 21 Sep 2021 12:08:44 +0300

**Comment by memejim8** [comment]
Update: 1.3 version doesnt work either
