### ISSUE TITLE
The game crashes when creating/entering a world

### ISSUE THREAD

**Issue by Juaum1241** [miyo6032/bosses-of-mass-destruction#58]
This happens whenever i try to create or enter a world with the 1.17.1 version of this mod

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 17/03/2022 09:29
Description: Exception in server tick loop

dev.onyxstudios.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Bosses of Mass Destruction (Beta) (bosses_of_mass_destruction)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:171)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:105)
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
	at dev.onyxstudios.cca.internal.entity.StaticEntityComponentPlugin.requiresStaticFactory(StaticEntityComponentPlugin.java:66)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.getEntityFactory(CardinalEntityInternals.java:70)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$0(CardinalEntityInternals.java:57)
	at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:308)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:55)
	at net.minecraft.class_1297.handler$zpm000$initDataTracker(class_1297.java:8032)
	at net.minecraft.class_1297.<init>(class_1297.java:280)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1308.<init>(class_1308.java:122)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_3988.<init>(class_3988.java:55)
	at net.hat.gt.entities.AbstractGoblinEntity.<init>(AbstractGoblinEntity.java:72)
	at net.hat.gt.entities.GoblinTraderEntity.<init>(GoblinTraderEntity.java:20)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.hat.gt.spawning.SpawnHandler$WorldLoad.onWorldLoad(SpawnHandler.java:29)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$cao000$onLoadWorld(MinecraftServer.java:3835)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:384)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350)
	at net.minecraft.class_1132.method_3823(class_1132.java:71)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/world/WorldComponentInitializer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:168)
	... 26 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.world.WorldComponentInitializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1408241760 bytes (1343 MiB) / 2080374784 bytes (1984 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2,50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8280
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095,00
	Graphics card #1 deviceId: 0x1f99
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 21359,05
	Virtual memory used (MB): 8822,78
	Swap memory total (MB): 14848,00
	Swap memory used (MB): 35,29
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 2.2.0
		adventurez: AdventureZ 1.4.3
		amecsapi: Amecs API 1.1.5+mc21w16a
		apoli: Apoli 2.0.5
		apugli: Apugli 1.1.5
		architectury: Architectury 2.10.6
		artifacts: Artifacts 5.0.2+fabric
		artifality: Artifality 0.4.3
		axolotlitemfix: Axolotl Item Fix 1.1.2
		backslot: BackSlot 1.2.2
		backslotaddon: BackSlot Addon 1.0.7
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.0
		boatcontainer: BoatContainer 1.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		caffeineconfig: CaffeineConfig 1.0.0
		calio: Calio 1.3.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cavebiomes: Cave Biomes 0.6.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.3.58
		collective-fabric: Collective (Fabric) 4.25
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cosmetic-armor: Cosmetic Armor 1.1.0
		cosmetica: Cosmetica 0.3.0
		deathcoords: Death Coords 1.0.0
		dehydration: Dehydration 1.2.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dragonloot: DragonLoot 1.0.9
		dualwielding: Dual Wielding 1.0.7
		dummmmmmy: MmmMmmMmmMmm 1.17-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49-fabric
		elytratrinket: Elytra Trinket 3.0.0-1.17.1
		enchant_giver: Enchant Giver 1.1.0
		endrem: End Remastered 4.1.0
		expandability: ExpandAbility 4.0.2
		extraorigins: Extra Origins 1.17-11
		fabric: Fabric API 0.46.0+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.0+4a20890318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.13.3
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		geckolib3: Geckolib 3.0.32
		genesis: Genesis 0.8
		goblintraders: Goblin Traders 1.4.0
		hookshot: Hookshot 22.0
		ibarnorigins: ibarn's origins addon 1.0.5
		impaled: Impaled 1.0.1
		inmis: Inmis 2.3.2-1.17.1
		inventorysorter: Inventory Sorter 1.8.0-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.4.0.1
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		mcdw: MC Dungeons Weapons 3.6.0
		medievalorigins: Medieval Origins 3.0.2
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.17.1
		moborigins: Mob Origins 1.7.0
		modmenu: Mod Menu 2.0.2
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousetweaks: Mouse Tweaks 2.15
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		mythic-mounts: Mythic Mounts 1.17.1-5.0
		nibbles: Nibbles 1.1.0
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_joml_joml: joml 1.10.2
		origins: Origins 1.1.4
		origins-classes: Origins: Classes 1.2.2
		outvoted: Outvoted 1.5.0-rc.1
		owo: oωo 0.3.2+1.17
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.3.0
		polymorph: Polymorph 0.0.15-1.17.1
		quartzelv: Quartz Elevator 1.3.0+1.17
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.5.433
		rpgdifficulty: Rpg Difficulty 1.0.7
		rpgz: RPGZ 0.4.10
		satin: Satin 1.6.4
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		sodium: Sodium 0.3.4+build.13
		sodium-extra: Sodium Extra 0.4.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stuffz: StuffZ 2.3.2
		terralith: Terralith for Fabric 1.5.1
		things: Things 0.2.7
		tho: THOrigins 1.0.0
		thonkutil: ThonkUtil 1.2.1
		toomanyorigins: TooManyOrigins 0.2.2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 1.1.0-beta
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.4
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		villagernames: Villager Names 2.0.1
		voidwalker: Voidwalker 1.17-8
		voidz: VoidZ 1.0.5
		waystones: Waystones 2.2.3
		wolveswitharmor: Wolves With Armor 1.6.2-1.17.1
		wthit: wthit 3.11.2
		yungsapi: YUNG's API 1.17-Fabric-19
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by miyo6032** [comment]
You are missing cardinal components api I think
