### ISSUE TITLE
void blossom cavern piece generator errors with c2me fabric 1.18.2

### ISSUE THREAD

**Issue by TheRanker** [miyo6032/bosses-of-mass-destruction#59]
this causes tremedous amounts of lag wihtin the world

[23:44:37] [C2ME worker #3/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:126) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:142) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:37] [C2ME worker #3/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:126) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:132) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:37] [C2ME worker #3/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd001$onGetChunk(class_3233.java:2067) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:126) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:132) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:37] [C2ME worker #1/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:125) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:142) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:37] [C2ME worker #1/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:125) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:132) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:38] [C2ME worker #1/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:127) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:142) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[23:44:40] [C2ME worker #1/WARN]: Potential dangerous call with reducedLockRadius
java.lang.Throwable: null
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder$StacktraceHolder.<init>(StacktraceRecorder.java:71) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at com.ishland.c2me.common.threading.worldgen.debug.StacktraceRecorder.record(StacktraceRecorder.java:38) ~[c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar:?]
	at net.minecraft.class_3233.handler$bkd000$onIsChunkLoaded(class_3233.java:2074) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8393(class_3233.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8402(class_3233.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:141) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8392(class_3233.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_3233.method_8320(class_3233.java:151) ~[server-intermediary.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:127) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator$generateCave$canReplace$1.invoke(VoidBlossomCavernPieceGenerator.kt:124) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.replaceBlock(VoidBlossomCavernPieceGenerator.kt:164) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generateCave(VoidBlossomCavernPieceGenerator.kt:132) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.void_blossom_cavern.VoidBlossomCavernPieceGenerator.generate(VoidBlossomCavernPieceGenerator.kt:46) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.barribob.boss.structure.util.CodeStructurePiece.method_14931(CodeStructurePiece.kt:44) ~[BOMD-1.3.6-1.18.2.jar:?]
	at net.minecraft.class_3449.method_14974(class_3449.java:60) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(class_2794.java:438) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:437) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.mdcdb382$lambda$runGenerationTask$0$3(class_2806.java:1091) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by miyo6032** [comment]
I ran these two together and went to the structure and was unable to replicate the errors and the lag. Is there something else you did that I am not aware of

**Comment by TheRanker** [comment]
nope.. not a thing.. i use c2me as indicated in the log to help with world gen.  maybe a conflict there. but the error is filling up the logs and tps drops a lot when it happens
