### ISSUE TITLE
Incendium / nullscape incompatibility    -- works with teralith

### ISSUE THREAD

**Issue by Tiagoez** [miyo6032/bosses-of-mass-destruction#65]
[22:03:49] [Server thread/WARN]: Couldn't create template entity of bosses_of_mass_destruction:obsidilith (class net.minecraft.class_1297)... Defaulting to empty
java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$bosses_of_mass_destruction$event_scheduler()" because "<parameter1>" is null
	at dev.onyxstudios.cca._generated_.ComponentType$bosses_of_mass_destruction$event_scheduler.getInternal(Unknown Source) ~[?:?]
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at net.barribob.boss.cardinalComponents.ModComponents$Companion.getWorldEventScheduler(ModComponents.kt:35) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.mobs.obsidilith.BurstAction.<init>(BurstAction.kt:22) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.mobs.obsidilith.ObsidilithEntity.<init>(ObsidilithEntity.kt:52) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities$OBSIDILITH$1.invoke(Entities.kt:81) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities$OBSIDILITH$1.invoke(Entities.kt:80) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities.registerConfiguredMob$lambda-0(Entities.kt:115) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:478) ~[server-intermediary.jar:?]
	at eu.pb4.polymer.impl.entity.InternalEntityHelpers.getEntity(InternalEntityHelpers.java:50) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:255) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at net.minecraft.class_3324.localvar$cmn000$polymer_setupHandler(class_3324.java:9451) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:170) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.md543d77$lambda$polymer_prePlayHandshakeHackfest$0$0(class_3248.java:2032) ~[server-intermediary.jar:?]
	at eu.pb4.polymer.impl.networking.PolymerHandshakeHandlerImplLogin.method_12082(PolymerHandshakeHandlerImplLogin.java:141) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at net.minecraft.class_2827.method_12266(class_2827.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2827.method_11054(class_2827.java:6) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zld000$modifiedRunLoop(MinecraftServer.java:4905) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:03:49] [Server thread/WARN]: Couldn't create template entity of bosses_of_mass_destruction:gauntlet (class net.minecraft.class_1297)... Defaulting to empty
java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$bosses_of_mass_destruction$event_scheduler()" because "<parameter1>" is null
	at dev.onyxstudios.cca._generated_.ComponentType$bosses_of_mass_destruction$event_scheduler.getInternal(Unknown Source) ~[?:?]
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83) ~[cardinal-components-base-4.1.4-5cbea34fcb0886.jar:?]
	at net.barribob.boss.cardinalComponents.ModComponents$Companion.getWorldEventScheduler(ModComponents.kt:35) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.mobs.gauntlet.GauntletEntity.<init>(GauntletEntity.kt:65) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities$GAUNTLET$1.invoke(Entities.kt:85) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities$GAUNTLET$1.invoke(Entities.kt:84) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.barribob.boss.mob.Entities.registerConfiguredMob$lambda-0(Entities.kt:115) ~[BOMD-1.3.7-1.18.2.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:478) ~[server-intermediary.jar:?]
	at eu.pb4.polymer.impl.entity.InternalEntityHelpers.getEntity(InternalEntityHelpers.java:50) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:255) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at net.minecraft.class_3324.localvar$cmn000$polymer_setupHandler(class_3324.java:9451) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:170) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.md543d77$lambda$polymer_prePlayHandshakeHackfest$0$0(class_3248.java:2032) ~[server-intermediary.jar:?]
	at eu.pb4.polymer.impl.networking.PolymerHandshakeHandlerImplLogin.method_12082(PolymerHandshakeHandlerImplLogin.java:141) ~[polymer-0.2.0-beta.36+1.18.2-e16a7ece54e7132.jar:?]
	at net.minecraft.class_2827.method_12266(class_2827.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2827.method_11054(class_2827.java:6) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zld000$modifiedRunLoop(MinecraftServer.java:4905) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

the boss cant be located with the command /locate before actually seeing a structure
but we managed to find a boss 
so there is an error but it still work 
im not sure if its a good issue or a real bug i jst wanted to prevent you

**Comment by miyo6032** [comment]
This error is unrelated to the issue - that is due to some other mod.
The reason why the boss can't be located is that the mods add lots of biomes and need to manually be added to make the structure generate. So currently there aren't very many biomes to spawn in so it makes them rare. I will see if I can add their biomes
