### ISSUE TITLE
Game refuses to open (pretty sure i have all the dependencies?)

### ISSUE THREAD

**Issue by pebblemuncher65** [miyo6032/bosses-of-mass-destruction#66]
---- Minecraft Crash Report ----
// Don't do that.

Time: 6/9/22, 9:54 PM
Description: Initializing game

java.lang.NoSuchMethodError: 'void software.bernie.geckolib3.core.controller.AnimationController.addModelFetcher(java.util.function.Function)'
	at net.barribob.boss.render.ModGeoRenderer.<clinit>(ModGeoRenderer.java:172)
	at net.barribob.boss.mob.Entities$clientInit$5.create(Entities.java:178)
	at net.fabricmc.fabric.api.client.rendereregistry.v1.EntityRendererRegistry.initialize(EntityRendererRegistry.java:82)
	at net.minecraft.class_898.handler$cfn000$onRegisterRenderers(class_898.java:1103)
	at net.minecraft.class_898.method_23167(class_898.java:185)
	at net.minecraft.class_898.<init>(class_898.java:192)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.barribob.boss.render.ModGeoRenderer.<clinit>(ModGeoRenderer.java:172)
	at net.barribob.boss.mob.Entities$clientInit$5.create(Entities.java:178)
	at net.fabricmc.fabric.api.client.rendereregistry.v1.EntityRendererRegistry.initialize(EntityRendererRegistry.java:82)
	at net.minecraft.class_898.handler$cfn000$onRegisterRenderers(class_898.java:1103)
	at net.minecraft.class_898.method_23167(class_898.java:185)
	at net.minecraft.class_898.<init>(class_898.java:192)
	at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by miyo6032** [comment]
Ok, I think I will need to fix, but for now, you can use a slightly earlier version of geckolib library and it should work

**Comment by pebblemuncher65** [comment]
gotcha, thanks!

**Comment by miyo6032** [comment]
Ok, I think maybe geckolib reverted their changes so with 3.0.79 it seems to be working fine again
