### ISSUE TITLE
The Log you requested btw this is Sgt_Savag3

### ISSUE THREAD

**Issue by sgtsavage123** [miyo6032/bosses-of-mass-destruction#9]
MultiMC version: 0.6.12-1530

Minecraft folder is:
C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/instances/wooooooooooooooooooork/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_241/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_241, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/instances/wooooooooooooooooooork/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader/0.11.3/fabric-loader-0.11.3.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] BOMD-1.0.2-1.16.5
  [✔️] fabric-api-0.34.1+1.16
  [✔️] fabric-language-kotlin-1.5.0+kotlin.1.4.31
  [✔️] geckolib-fabric-1.16.5-3.0.33

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/instances/wooooooooooooooooooork/.minecraft --assetsDir C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms204m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 7072

Using onesix launcher.

[17:29:43] [main/INFO]: Loading for game Minecraft 1.16.5
[17:29:43] [main/INFO]: [FabricLoader] Loading 64 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, fabric-structure-api-v1@1.1.4+ca58154a7d, maelstrom_library@1.2-1.16.5, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, bosses_of_mass_destruction@1.0.2-1.16.5, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.34.1+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, fabric-entity-events-v1@1.1.0+c88702897d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.6+2868a2287d, autoconfig1u@3.3.1, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, cardinal-components-world@2.7.10, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.7.10, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.7.10, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.2+d6244c6d7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d, geckolib3@3.0.33, multipart_entities@1.1.1-SNAPSHOT
[17:29:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Owner/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:29:51] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:29:53] [main/INFO]: Setting user: S3rg3ant_Savag3
[17:29:54] [main/INFO]: [Indigo] Registering Indigo renderer!
[17:29:55] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:30:00] [main/INFO]: Narrator library for x64 successfully loaded
[17:30:01] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Maelstrom Library, Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Bosses of Mass Destruction (Beta), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0), Geckolib)
[17:30:14] [main/INFO]: OpenAL initialized.
[17:30:14] [main/INFO]: Sound engine started
[17:30:15] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:30:15] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:30:15] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:30:15] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:30:15] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:30:15] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:30:15] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:30:16] [main/INFO]: Created: 512x512x0 minecraft:textures/atlas/particles.png-atlas
[17:30:16] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:30:16] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:30:21] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:30:21] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:21] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:21] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:30:21] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:21] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Bosses of Mass Destruction (Beta), Fabric Tool Attribute API (v1))
[17:30:23] [main/INFO]: Loaded 7 recipes
[17:30:23] [main/INFO]: Loaded 930 advancements
[17:30:23] [main/INFO]: Applied 9 biome modifications to 9 of 79 new biomes in 41.71 ms
[17:30:23] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[17:30:24] [main/ERROR]: WorldGenSettings: Unknown registry key: betterend:better_end_biome_source missed input: {"minecraft:the_end":{generator:{settings:"minecraft:end",seed:4357915110235270918L,biome_source:{seed:4357915110235270918L,type:"betterend:better_end_biome_source"},type:"minecraft:noise"},type:"minecraft:the_end"}}
[17:30:26] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:30:26] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:26] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:26] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:30:26] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:30:26] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Bosses of Mass Destruction (Beta), Fabric Tool Attribute API (v1))
[17:30:28] [main/INFO]: Loaded 7 recipes
[17:30:28] [main/INFO]: Loaded 930 advancements
[17:30:28] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[17:30:28] [main/ERROR]: WorldGenSettings: Unknown registry key: betterend:better_end_biome_source missed input: {"minecraft:the_end":{generator:{settings:"minecraft:end",seed:4357915110235270918L,biome_source:{seed:4357915110235270918L,type:"betterend:better_end_biome_source"},type:"minecraft:noise"},type:"minecraft:the_end"}}
[17:30:29] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:30:29] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[17:30:29] [Server thread/INFO]: Generating keypair
[17:30:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at net.minecraft.class_1937.mdedc5c8$lambda$static$0$0(class_1937.java:1233) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3528.method_15332(class_3528.java:16) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1937.handler$zzi000$initComponents(class_1937.java:1240) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1937.<init>(class_1937.java:153) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.<init>(class_3218.java:186) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:67) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56) ~[3eda86fc-c8be-44b9-8fbe-7097c6b692d8.jar:?]
	... 11 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_241]
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52) ~[3eda86fc-c8be-44b9-8fbe-7097c6b692d8.jar:?]
	... 11 more
[17:30:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Owner\Downloads\mmc-stable-win32\MultiMC\instances\wooooooooooooooooooork\.minecraft\crash-reports\crash-2021-05-06_17.30.29-server.txt
[17:30:29] [Server thread/INFO]: Stopping server
[17:30:29] [Server thread/INFO]: Saving players
[17:30:29] [Server thread/INFO]: Saving worlds
[17:30:29] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:572) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:599) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:203) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 06/05/21 17:30
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at net.minecraft.class_1937.mdedc5c8$lambda$static$0$0(class_1937.java:1233)
	at net.minecraft.class_3528.method_15332(class_3528.java:16)
	at net.minecraft.class_1937.handler$zzi000$initComponents(class_1937.java:1240)
	at net.minecraft.class_1937.<init>(class_1937.java:153)
	at net.minecraft.class_3218.<init>(class_3218.java:186)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
	at net.minecraft.class_1132.method_3823(class_1132.java:67)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56)
	... 11 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Unknown Source)
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 294743040 bytes (281 MB) / 1056964608 bytes (1008 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms204m -Xmx2048m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		geckolib3: Geckolib 3.0.33
		java: Java HotSpot(TM) 64-Bit Server VM 8
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		minecraft: Minecraft 1.16.5
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Owner\Downloads\mmc-stable-win32\MultiMC\instances\wooooooooooooooooooork\.minecraft\crash-reports\crash-2021-05-06_17.30.29-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by miyo6032** [comment]
Seems like the newest version of the fabric API broke cardinal components. Using fabric-api-0.34.1+1.16 I get the same crash. Try downloading an older version. fabric-api-0.32.9+1.16 seems to work for me.

**Comment by sgtsavage123** [comment]
i just checked and it works thankyou
