### ISSUE TITLE
Spore Blossom Fireball Attack Crash (1.19.3)

### ISSUE THREAD

**Issue by TheTrueTrident** [miyo6032/bosses-of-mass-destruction#95]
Was using this mod while playing with a few other Vanilla+ mods and I cant seem to defeat this boss due to this crash.

java.lang.AbstractMethodError: Receiver class net.barribob.boss.render.ModGeoRenderer does not define or inherit an implementation of the resolved method 'abstract boolean firePreRenderEvent(net.minecraft.class_4587, software.bernie.geckolib.cache.object.BakedGeoModel, net.minecraft.class_4597, float, int)' of interface software.bernie.geckolib.renderer.GeoRenderer.
	at software.bernie.geckolib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:127)
	at net.barribob.boss.render.ModGeoRenderer.method_3936(ModGeoRenderer.kt:92)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-
FULL LOG:

[crash-2023-03-02_15.59.13-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/10875759/crash-2023-03-02_15.59.13-client.txt)

**Comment by miyo6032** [comment]
You can try downgrading geckolib to a bit older version

**Comment by miyo6032** [comment]
Actually I think you can upgrade BOMD to 1.5.1 as well to fix
